### ISSUE TITLE
Error while /sell items

### ISSUE THREAD

**Issue by DaveDevil** [DeveloperRic/CustomShop#12] opened 2017-07-11 14:25 UTC
Hello

When I use the /sell command and I insert into the tab particular objects (I still do not understand why some are and others do not), objects are taken without receiving money, and the console displays the following error:

`[16:19:58 ERROR]: Could not pass event InventoryCloseEvent to CustomShop v2.0.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:884) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1629) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:1) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at com.rictacius.customShop.Sell.checkShops(Sell.java:28) ~[?:?]
        at com.rictacius.customShop.Sell.onExit(Sell.java:85) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor281.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        ... 16 more
`

**Comment by Megazac1** [comment] 2017-07-13 04:14
Same error for me as well.  From the same action.

[19:51:16] [Server thread/INFO]: americanpilot8 issued server command: /sell
[19:51:20] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to CustomShop v2.0.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:882) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1619) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
	at net.minecraft.server.v1_11_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
	at net.minecraft.server.v1_11_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:1) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.NumberFormatException: For input string: "38.5"
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_45]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_45]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_45]
	at com.rictacius.customShop.Sell.checkShops(Sell.java:34) ~[?:?]
	at com.rictacius.customShop.Sell.onExit(Sell.java:92) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor215.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot_1.11.2.jar:git-Spigot-7d78b81-a867313]
	... 16 more

**Comment by DeveloperRic** [comment] 2017-07-13 20:07
Guys, I'm in the middle of fixing a major issue with my back-end code, due to a change of host. I will begin fixing this, once the major issue is resolved. Sorry for any inconveniences this may have caused. For now feel free to disable the plugin on your server. It will be fixed ASAP.

**Comment by DeveloperRic** [comment] 2017-07-14 14:02
For the first error, this is where it arises:

int sellTypeData = Integer.parseInt(data[0].split(":")[1]);

This means that you have configured your shops.yml file incorrectly, and Custom Shop is unable to parse that specific item. You can identify which item is causing the error by adding them one by one and using /shop reload to reload the shops.

**Comment by DeveloperRic** [comment] 2017-07-14 14:45
For the second error, you have one or two problems:

1. You are not running the latest version of Custom shop, you can download that [here](victorolaitan.xyz/ric).
2. You have configured your shops.yml file incorrectly. Follow the same instructions I sent earlier to fix this.

**Comment by DaveDevil** [comment] 2017-07-14 23:20
I have checked ingame with the shops.yml

it seems to be every item that is "not vendible" with the "-" in the PRICE_SELL field

for example, crafting table or the glass:

craftingtable: '58:0,1,2,0,-'
glass: '20:0,32,100,0,-'

here's my shop.yml:
https://pastebin.com/j1Smr9QJ

**Comment by DeveloperRic** [comment] 2017-07-15 09:33
Try putting a dash in both the sell amount and sell price fields.

**Comment by DaveDevil** [comment] 2017-07-15 10:03
Done, i set as this:

craftingtable: '58:0,1,2,-,-'

same error in console, item taken and no money given

**Comment by DeveloperRic** [comment] 2019-08-15 14:29
Are you still having this issue?

**Comment by DeveloperRic** [comment] 2021-11-14 04:08
@DaveDevil @Megazac1 please update to the latest version and reopen if you still have issues

**Closed as completed by DeveloperRic** 2021-11-14 04:08 UTC
